/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.interpixel.siloproject;

import java.awt.Color;
import java.awt.event.*;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author Julius
 */
public class BuatSJForm extends javax.swing.JPanel {

    private MainPage mainPage;

    /**
     * Creates new form BuatSJForm
     */
    public BuatSJForm(MainPage mainPage) {
        initComponents();
        tanggalOrderTxt.setText(LocalDate.now().toString());
        itemsTxtPlaceholder();
        this.addMainPage(mainPage);
    }
    
    private void addMainPage(MainPage mainPage) {
        this.mainPage = mainPage;
    }

    private void itemsTxtPlaceholder() {
        itemsTxt.setForeground(Color.GRAY);
        itemsTxt.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (itemsTxt.getText().equals("(Amount) (Barcode/Nama), Ex: 4 321354, 2 Thermogun Devices")) {
                    itemsTxt.setText("");
                    itemsTxt.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (itemsTxt.getText().isEmpty()) {
                    itemsTxt.setForeground(Color.GRAY);
                    itemsTxt.setText("(Amount) (Barcode/Nama), Ex: 4 321354, 2 Thermogun Devices");
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomorSJLbl = new javax.swing.JLabel();
        nomorInvoiceLbl = new javax.swing.JLabel();
        nomorInvoiceTxt = new javax.swing.JTextField();
        nomorSJTxt = new javax.swing.JTextField();
        namaCustomerTxt = new javax.swing.JTextField();
        emailCustomerTxt = new javax.swing.JTextField();
        tanggalOrderTxt = new javax.swing.JTextField();
        tanggalOrderLbl = new javax.swing.JLabel();
        emailCustomerLbl = new javax.swing.JLabel();
        namaCustomerLbl = new javax.swing.JLabel();
        itemsLbl = new javax.swing.JLabel();
        buatSJBtn = new javax.swing.JButton();
        itemsTxt = new javax.swing.JTextField();

        nomorSJLbl.setText("Nomor SJ");

        nomorInvoiceLbl.setText("Nomor Invoice");

        nomorInvoiceTxt.setToolTipText("");

        nomorSJTxt.setToolTipText("");

        namaCustomerTxt.setToolTipText("");

        emailCustomerTxt.setToolTipText("");

        tanggalOrderTxt.setEditable(false);
        tanggalOrderTxt.setToolTipText("");

        tanggalOrderLbl.setText("Tanggal Order");

        emailCustomerLbl.setText("Email Customer");

        namaCustomerLbl.setText("Nama Customer");

        itemsLbl.setText("Items");

        buatSJBtn.setText("Buat SJ");
        buatSJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buatSJBtnActionPerformed(evt);
            }
        });

        itemsTxt.setForeground(new java.awt.Color(153, 153, 153));
        itemsTxt.setText("(Amount) (Barcode/Nama), Ex: 4 321354, 2 Thermogun Devices");
        itemsTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemsTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomorSJLbl)
                    .addComponent(namaCustomerLbl)
                    .addComponent(emailCustomerLbl)
                    .addComponent(nomorInvoiceLbl)
                    .addComponent(tanggalOrderLbl)
                    .addComponent(itemsLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buatSJBtn)
                    .addComponent(nomorInvoiceTxt)
                    .addComponent(tanggalOrderTxt)
                    .addComponent(emailCustomerTxt)
                    .addComponent(namaCustomerTxt)
                    .addComponent(nomorSJTxt)
                    .addComponent(itemsTxt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomorInvoiceLbl)
                    .addComponent(nomorInvoiceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomorSJLbl)
                    .addComponent(nomorSJTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaCustomerLbl)
                    .addComponent(namaCustomerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailCustomerLbl)
                    .addComponent(emailCustomerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tanggalOrderLbl)
                    .addComponent(tanggalOrderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemsLbl))
                .addGap(18, 18, 18)
                .addComponent(buatSJBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buatSJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buatSJBtnActionPerformed
        int dialogResult = mainPage.tampilkanConfirmDialog();
        if(dialogResult != JOptionPane.YES_OPTION) {return;}

        // if itemsTxt.getText is the placeholder, set it to null
        String itemsStr = itemsTxt.getText();
        if (itemsStr.equals("(Amount) (Barcode/Nama), Ex: 4 321354, 2 Thermogun Devices")) {
            itemsStr = null;
        }

        String[] input = {
            nomorInvoiceTxt.getText(),
            nomorSJTxt.getText(),
            namaCustomerTxt.getText(),
            emailCustomerTxt.getText(),
            tanggalOrderTxt.getText(),
            itemsStr
        };
        mainPage.confirmBuatSJ(input);

    }//GEN-LAST:event_buatSJBtnActionPerformed

    private void itemsTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemsTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemsTxtActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buatSJBtn;
    private javax.swing.JLabel emailCustomerLbl;
    private javax.swing.JTextField emailCustomerTxt;
    private javax.swing.JLabel itemsLbl;
    private javax.swing.JTextField itemsTxt;
    private javax.swing.JLabel namaCustomerLbl;
    private javax.swing.JTextField namaCustomerTxt;
    private javax.swing.JLabel nomorInvoiceLbl;
    private javax.swing.JTextField nomorInvoiceTxt;
    private javax.swing.JLabel nomorSJLbl;
    private javax.swing.JTextField nomorSJTxt;
    private javax.swing.JLabel tanggalOrderLbl;
    private javax.swing.JTextField tanggalOrderTxt;
    // End of variables declaration//GEN-END:variables
}
