/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.interpixel.siloproject;

/**
 *
 * @author Julius
 */
public class EmailSJForm extends javax.swing.JPanel {

    private SuratJalan suratJalan;
    private MainPage mainPage;

    /**
     * Creates new form EmailSJForm
     * @param mainPage
     * @param suratJalan
     */
    public EmailSJForm(MainPage mainPage, SuratJalan suratJalan) {
        initComponents();
        this.suratJalan = suratJalan;
        addMainPage(mainPage);
        fillDefaults();
    }

    private void addMainPage(MainPage mainPage) {
        this.mainPage = mainPage;
    }
    
    private void fillDefaults() {
        emailToTxt.setText(suratJalan.emailCustomer);
        emailSubjectTxt.setText("Surat Jalan SILO");
        emailBodyTxt.setText(suratJalan.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emailToLbl = new javax.swing.JLabel();
        emailToTxt = new javax.swing.JTextField();
        emailSubjectLbl = new javax.swing.JLabel();
        emailSubjectTxt = new javax.swing.JTextField();
        emailBodyLbl = new javax.swing.JLabel();
        sendBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        emailBodyTxt = new javax.swing.JTextArea();

        emailToLbl.setText("To");

        emailToTxt.setToolTipText("");

        emailSubjectLbl.setText("Subject");

        emailSubjectTxt.setToolTipText("");

        emailBodyLbl.setText("Text");

        sendBtn.setText("Send");
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });

        emailBodyTxt.setColumns(20);
        emailBodyTxt.setRows(5);
        jScrollPane1.setViewportView(emailBodyTxt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sendBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailSubjectLbl)
                            .addComponent(emailBodyLbl)
                            .addComponent(emailToLbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emailSubjectTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(emailToTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailToLbl)
                    .addComponent(emailToTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailSubjectLbl)
                    .addComponent(emailSubjectTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailBodyLbl)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(sendBtn)
                .addContainerGap(120, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        mainPage.emailSJ(emailToTxt.getText(),
                emailSubjectTxt.getText(), 
                emailBodyTxt.getText()
        );
    }//GEN-LAST:event_sendBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emailBodyLbl;
    private javax.swing.JTextArea emailBodyTxt;
    private javax.swing.JLabel emailSubjectLbl;
    private javax.swing.JTextField emailSubjectTxt;
    private javax.swing.JLabel emailToLbl;
    private javax.swing.JTextField emailToTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton sendBtn;
    // End of variables declaration//GEN-END:variables
}
